theme: jekyll-theme-cayman
project-name: Google Assistant for PC, Linux and MacOS.
project-tagline: Google assistant is unofficially made by Melvin Abraham (this is an fanmade page), it works so well! Try it
